dist: bionic
sudo: required

before_install:
    - sudo apt-add-repository -y ppa:beineri/opt-qt-5.12.0-bionic
    - sudo apt-get update
    - sudo apt-get -y install
        g++-4.8
        libc6-i386
        qt512tools
        qt512svg
        qt512webengine
        qt512serialport
        libboost-chrono-dev
        libboost-system-dev
        libgl1-mesa-dev
    - PATH="/opt/qt512/bin:$PATH"
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
    - qt512-env.sh
    - mkdir -p build/.lib/


install:
    # install astyle
    - wget 'https://s3-us-west-2.amazonaws.com/ucsolarteam.hostedfiles/astyle'
    - tar -zxvf astyle
    - (cd astyle/build/gcc && make release && sudo make install)
    - rm astyle -rf
    # install googletest and googlemock
    - git clone https://github.com/google/googletest.git
    - sudo cp -r googletest/googletest/include/gtest /usr/local/include
    - sudo cp -r googletest/googlemock/include/gmock /usr/local/include
    - (cd googletest &&
       g++ -std=c++11
           -isystem googletest/include/
           -Igoogletest
           -isystem googlemock/include/
           -Igooglemock
           -pthread
           -c
           googlemock/src/gmock-all.cc &&
       g++ -std=c++11
           -isystem googletest/include/
           -Igoogletest
           -isystem googlemock/include/
           -Igooglemock
           -pthread
           -c
           googletest/src/gtest-all.cc &&
       ar -rv libgmock.a gtest-all.o gmock-all.o)
    - cp googletest/libgmock.a build/.lib/
    # install rabbitmq-c
    - git clone https://github.com/alanxz/rabbitmq-c
    - sudo cp rabbitmq-c/librabbitmq/*.h /usr/local/include/
    - mkdir rabbitmq-c/build
    - (cd rabbitmq-c/build && cmake .. && cmake --build .)
    - sudo cp rabbitmq-c/build/librabbitmq/librabbitmq.a /usr/local/lib/
    - sudo cp rabbitmq-c/build/librabbitmq/*.so* /usr/local/lib/
    # install SimpleAmqpClient
    - git clone https://github.com/alanxz/SimpleAmqpClient
    - mkdir SimpleAmqpClient/build
    - (cd SimpleAmqpClient/build &&
       cmake -DRabbitmqc_INCLUDE_DIR=../../rabbitmq-c/librabbitmq
             -DRabbitmqc_LIBRARY=../../rabbitmq-c/build/librabbitmq
             .. &&
       make)
    - sudo mkdir /usr/local/include/SimpleAmqpClient
    - sudo cp SimpleAmqpClient/build/*.so* /usr/local/lib/
    - sudo cp SimpleAmqpClient/src/SimpleAmqpClient/*.h /usr/local/include/SimpleAmqpClient/

script:
    - "! (astyle *.h *.cpp -r
                           --dry-run
                           --options=astylerc
                           --exclude=googletest
                           --exclude=SimpleAmqpClient
                           --exclude=rabbitmq-c |
          grep Formatted)"
    - cd src
    - qmake
    - make
    - make check

language: cpp

