dist: bionic
sudo: required

before_install:
    - sudo apt-add-repository -y ppa:beineri/opt-qt-5.12.0-bionic
    - sudo apt-get update
    - sudo apt-get -y install
        g++-4.8
        libc6-i386
        qt512tools
        qt512svg
        qt512webengine
        qt512serialport
        libboost-chrono-dev
        libboost-system-dev
        libgl1-mesa-dev
        python3-pip
        python3-setuptools
    - PATH="/opt/qt512/bin:$PATH"
    - export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/usr/local/lib
    - qt512-env.sh

install:
    # install astyle
    - wget 'https://s3-us-west-2.amazonaws.com/ucsolarteam.hostedfiles/astyle'
    - tar -zxvf astyle
    - (cd astyle/build/gcc && make release && sudo make install)
    - rm astyle -rf
    # install conan
    - pip3 install conan
    - conan remote add conan-dbely https://api.bintray.com/conan/dbely/conan

script:
    - cd $TRAVIS_BUILD_DIR
    - "! (astyle *.h *.cpp -r
                           --dry-run
                           --options=astylerc
                           --exclude=googletest
                           --exclude=SimpleAmqpClient
                           --exclude=rabbitmq-c |
          grep Formatted)"
    - mkdir build && cd build
    - conan install .. --build=missing
    - qmake ../src/
    - make
    - make check

language: cpp

